# Generated by Django 5.2.14 on 2026-06-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_episode_item_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_locales', models.JSONField(blank=True, default=list)),
                ('subtitle_locales', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('mydublist', 'MyDubList'), ('crunchyroll', 'Crunchyroll')], default='manual', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='app.item')),
            ],
            options={
                'verbose_name_plural': 'anime availabilities',
            },
        ),
    ]
