# Generated by Django 5.2.14 on 2026-06-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '9001_animeavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.JSONField(blank=True, default=list)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_metadata', to='app.item')),
            ],
            options={
                'verbose_name_plural': 'item metadata',
            },
        ),
    ]
