# Generated by Django 5.2.14 on 2026-06-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '9002_itemmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_links', to='app.item')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
