# Generated by Django 5.2.14 on 2026-07-22 10:00
#
# Fork-side personal migration: E9.5 CrunchyrollCredential singleton (etp_rt store).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '9003_streaminglink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrunchyrollCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etp_rt', models.TextField(blank=True, default='')),
                ('etp_rt_vid', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crunchyroll credential',
                'verbose_name_plural': 'Crunchyroll credentials',
            },
        ),
    ]
