name: media-consumerus

services:
  app:
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - TZ=Europe/Berlin
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=yamtrack
      - DB_USER=yamtrack
      - DB_PASSWORD=yamtrack
      - DB_PORT=5432
    ports:
      - "127.0.0.1:${YAMTRACK_PORT:-7040}:8000"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=yamtrack
      - POSTGRES_USER=yamtrack
      - POSTGRES_PASSWORD=yamtrack
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
